### ISSUE TITLE
Emails transactionnels

### ISSUE THREAD

**Issue by lmag** [Eoxia/BeFlex-Sensei#2]

**Comment by lmag** [comment]
1 - Lorsque l'étudiant s'inscrit, il ne reçoit pas automatiquement de email de confirmation avec son identifiant et le lien pour paramétrer son mdp.

2 - Lorsque l'étudiant a fini le QUIZ, son certificat est édité dans l'espace admin (prof), mais pas dans son espace (abonné)

3 - L'étudiant ne reçoit pas non plus de email automatique avec son certificat dedans (PJ ou lien de téléchargement) . Il faudrait un email d'information lui expliquant où trouver son certificat sans avoir à le demander au prof.

**Comment by eoxia-amandine** [comment]
c'est OK
