### ISSUE TITLE
[ADD]Rendre obligatoire les noms et prénoms à l'inscription

### ISSUE THREAD

**Issue by lmag** [Eoxia/BeFlex-Sensei#8]
Rendre obligatoire lors de l'inscription : 
Noms
Prénoms
à l'inscription

**Comment by JulietteVillerabel** [comment]
![image](https://user-images.githubusercontent.com/62950212/116533214-67f2b780-a8e1-11eb-99a7-ff8d573130b8.png)

**Comment by lmag** [comment]
solution temporaire à la main
